.PHONY: clean All

All:
	@echo "----------Building project:[ Ferrari - Debug ]----------"
	@cd "Ferrari" && "$(MAKE)" -f  "Ferrari.mk"
clean:
	@echo "----------Cleaning project:[ Ferrari - Debug ]----------"
	@cd "Ferrari" && "$(MAKE)" -f  "Ferrari.mk" clean
